sudo: false
language: scala
services:
- redis-server
scala:
- 2.11
jdk:
- oraclejdk8
env:
  global:
  - BRIDGE_USER=travis
  - BRIDGE_ENV=dev
  - WEBSERVICES_URL="http://localhost"
  - HOST_POSTFIX="-dev.museborn.com"
  - UPLOAD_CMS_CERT_BUCKET="com-museborn-upload-cms-cert-dev"
  - CONSENTS_BUCKET="com-museborn-consents-dev"
  - UPLOAD_BUCKET="com-museborn-upload-dev"
  - UPLOAD_CMS_PRIV_BUCKET="com-museborn-upload-cms-priv-dev"
  - ATTACHMENT_BUCKET="com-museborn-deployment-dev"
  - secure: SsM07kjCSWjGTFDhkCtTuZdM5WrChFXgRmeMMRJr4JlbtJoaaVUXcXDofZ+4NrESiOvW7CiRXK6Oz3I9eL7vn8RCwlN5jf2OlmD4vKIiiINlvuuEe6hEu738RO7nUGN8SFh2k4ryzJ6XldghjBiBvBEqzVhwXteLhF3AVCsRB1s=
  - secure: kByWq5ygVVnXuBcHKhe6BdcGhUugS1Ux4nbrR/MY23KI7FC1vJ3LCx6N5TIVbOhjwCPwnWNfkydPlfO48hco6gpz8mJ6Sz7OdjyAWb1Ofx/XO5mI+8AIW0P1gXN9jbThSLEaTGUZlrDNfkcfkFUaLJHmmWOQ5CWCPzo5sw2cEDg=
  - secure: VSoOGViuAi98dBrveHw61gHz0zersdtn8raolu/uzpNQEI1csMdVr09SokygjtiSEt5uIVNma1zkuABRAEgfncT3rYqPq0mdeM+hxPEz2igxEMUXYHx3H9Osbo5oOrTZXnRg18kmzyupUQ98L5Y6/8lg67sgJkPBJEx9dwNKhMY=
  - secure: kTMnfr/AKb5Bp9HuNENNKHsMB+sdlxzIOptVFhA6Gg4poTw+6Y93yUHmqxtAh6WCnihG00877+uQw5IKUww0oL4ppbYgQKwyafhMeIkEpKG/Dycc80oklQe/n7mqHsgRpX3zCeKJG3AZmKsDj/l/WN1i01n68JMeOasGFFQYXpg=
  - secure: fFyFcdKI0utZGSTkeoukkVb4GHUuIpK5VA639prJHyrDhi/rxL8jU8A82av+lYBJHrCRN3ZMfgVxui4uLmqaSacPAcIBIeHyOFq9zEir7TDw8nXhsnAVLJt25i6L731hlEuNDfnroaHV5BCgfkECJcXee07UXhEKFk7vH80KeAk=
  - secure: buGUBaPnZuh8kUotK/iA8xJ0TibbCQpvSaxAwA7UxKlZI414cj8iuV01nsY+Kkwsjr6x0YZAGdzo5YbMFlZX/nsUBZQd8S+fSfm9vmeIBBl4KEmfYxguBpM0MrND1oQ3EYKNpFqlghuJPBsqWCOwfNF8yQALsU+JCdEL5RBqRmk=
  - secure: op8cOe2CvFxaj6GCLzqCVgSJzXofpqP90oS+66IUbECPUyUi6JuViaMGNzaM4mXcHPY5s8Ie0aa9nADlLf/ushBdzDD4/udIthUjU3FOj1azpX9c2qS5K5lLdKhLpqKHdnSm20Sll5AtgxDpfbcCin1Dty87G7N+mHyQtWghMtE=
  - secure: Z+qjzEGwJbnmSYpvb6FLa449FaRaMlHt31InRtlqZVpoKmGFY6hUofYdtBcDdwz/Y2X1QRyCOG88s/TpaNQo0lt7tOETwrkwAfQ6E97hnX7W/Gd4PhDAmkMc8w1PGtuvMl2/ZklLoNDUwbBC+U3tG1UcUlSiNheoAbRviQfFL00=
  - secure: tfbxUsq8+FVvICBJGZIKoWRkWYfQMrm5ODbYL2BnVgLnTBvAxX2tBjzuUkkEVG7eVmoKcIBbisbOIM2epi0lQ2cqHxwbYKb5Qr0EYBQOAl5wRNvbAdiuVmHQhoQtrPMw0uTbihJ8hqCdxN/l+n2lXcQkXeFxJN/9sA/Fm2uT9eU=
  - secure: HepX8b2aoAqu0MPuyEpy+PB2IbkTl/OE8h+CmWoaqDXLEPnYN0tQTdKAmqPk+G5VNb/UzNcCc4b4lMioKyJtx80eQo4io6R68lq/uG9FAkE20J6PhzxB9ZBRULi1BurxrE5lRj3RxU4lXn3bJJYyoormCqTSOai6nCtsIJ4MOaU=
  - secure: hG+O3ytuluFaq+Un3Y7uVrCTlVZWrBufVNd2WluKCNJ62zCUEhFgw43SO3g+/eRuhhPAos0n/y1KeOEpisFdFNCBthlHTA1solk2TVE7pVoJkEtv0DTdt9d5Dg3Rit7XA0QzsMvlErdZrCE7NhfjFe7clwnUQfgIEM7jVlsESro=
  - secure: R0bZSTX5dYjPSv9Skb3EtojMYPkl0hyFjLHknCE8+C1i9jrpT9iQFV3Xb0JrM9MEgdlbKtk19mYGfK7SFL8yjJIXYSR2a/Is5Q5+A7n9HCH1jyEoNDuem9EvCzbY5ywCpb7cHQ0TUK1tMdwDZ/OrMJ6No1eajI/hGRSni4kGcOU=
before_script:
- mkdir -p $HOME/.sbt/launchers/0.13.8/
- curl -L -o $HOME/.sbt/launchers/0.13.8/sbt-launch.jar http://dl.bintray.com/typesafe/ivy-releases/org.scala-sbt/sbt-launch/0.13.8/sbt-launch.jar
- mkdir -p $HOME/.bridge
- env
- bash  $TRAVIS_BUILD_DIR/dist/create_bridge_config.sh
- cat $HOME/.bridge/bridge-server.conf
script:
- sbt clean test dist
branches:
  only:
  - develop
  - uat
  - prod
deploy:
  - provider: heroku
    api_key:
      secure: dsrD0lN7luCXQCI+AK4wBZEWpxv/ji2xbbSMWWo3snBYb8CbuzqmH3KHSWStd9kSTKojWzatGFfIoIGGj6qoyG7gAk4E/PR1tb2Gelz+t6yWQUcRQclLHNd/WkozHLb5Z9Bg7N4HLcyupl7OMICixAaQ92+o2M+xhHq3/r2aOFs=
    app:
      develop: bridge-develop
      uat: bridge-uat
      prod: bridge-prod
  - provider: elasticbeanstalk
    skip_cleanup: true
    bucket_name: com-museborn-deployment
    zip_file: target/universal/bridgepf-0.1-SNAPSHOT.zip
    access_key_id: AKIAISLOVWVSED6LYRTA
    region: us-east-1
    app: BridgePF-beholt-dev
    env: beho-Brid-QOZ2FQ79L99N
    on:
      repo: consolecowboy/BridgePF
      branch: develop
